### ISSUE TITLE
What is C sharp

### ISSUE THREAD

**Issue by 0xPanic** [j-potter/FizzBuzz-cSharp#1]
Can you rewrite this in Java so i can run it on my machine

**Comment by kernelpanicatthedisco** [comment]
java is the best language

**Comment by 0xPanic** [comment]
actually can you rewrite it in R instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in go instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in lua instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in ruby instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in scala instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in erlang instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in Jscript instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in VBscript instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in python3.x instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in Javascript instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in visualbasic instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in x86 assembly instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in ARM assembly instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in MIPS assembly instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in SPARC assembly instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in PowerPC assembly instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in i-use-arch-btw brainfuck instead

**Comment by 0xPanic** [comment]
actually can you rewrite it in C# instead

**Comment by 0xPanic** [comment]
oh C# and C sharp are the same language. Ok nevermind @HackPotter

**Comment by HackPotter** [comment]
wontfix
